package tecladoswipe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author super
 */
public class DataConnect extends javax.swing.JPanel {

    /**
     * Creates new form DataConnect
     */
    public DataConnect() {
        initComponents();
        this.setSize(500,340);
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setLayout(null);

        jLabel1.setText("Insira a conexão: ");
        add(jLabel1);
        jLabel1.setBounds(30, 100, 170, 30);

        jTextField1.setText("jdbc:mysql://localhost:3306/Dicionario?");
        add(jTextField1);
        jTextField1.setBounds(200, 100, 250, 30);

        jLabel2.setText("Insira o nome do usuário: ");
        add(jLabel2);
        jLabel2.setBounds(30, 150, 150, 30);

        jTextField2.setText("root");
        add(jTextField2);
        jTextField2.setBounds(200, 150, 250, 30);

        jLabel3.setText("Insira a senha:");
        add(jLabel3);
        jLabel3.setBounds(30, 200, 160, 30);

        jButton1.setText("Testar Conexão");
        add(jButton1);
        jButton1.setBounds(200, 250, 130, 23);

        jButton2.setText("Continuar");
        add(jButton2);
        jButton2.setBounds(340, 250, 110, 23);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel4.setText("Teclado Swipe");
        add(jLabel4);
        jLabel4.setBounds(130, 20, 250, 60);

        jPasswordField1.setText("root");
        add(jPasswordField1);
        jPasswordField1.setBounds(200, 200, 250, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
