package tecladoswipe;

/**
 *
 * @author m78159
 */
public class Keyboard extends javax.swing.JFrame {
    ActionController ac;
    DataConnect dc;
    LayeredPane lp;
    DB db;
    /**
     * Creates new form Keyboard
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Keyboard() {
        super("Teclado Swipe");
        initComponents();
        this.setSize(500,340);
        ac = new ActionController(this);
        lp = new LayeredPane();
        this.getContentPane().add(lp);
        lp.setVisible(false);
        dc = new DataConnect();
        this.getContentPane().add(dc);
        db = new DB();
        lp.p.jTextField1.setEditable(false);
        lp.p.addMouseListener(ac); lp.p.jldelete.addActionListener(ac);
        dc.jButton1.addActionListener(ac);  dc.jButton2.addActionListener(ac);
        lp.p.jlspace.addActionListener(ac);    lp.p.jlshift.addActionListener(ac);
        lp.sp.forEach((sp) -> {sp.jl.forEach((jl)->{jl.addActionListener(ac);});});
        lp.p.jSug.forEach((jSug) -> {jSug.addActionListener(ac); jSug.addMouseListener(ac); jSug.addMouseMotionListener(ac);});
        lp.p.jl.forEach((jl) -> {jl.addActionListener(ac); jl.addMouseListener(ac); jl.addMouseMotionListener(ac);});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 340));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 340));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Keyboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
