package tecladoswipe;


import java.util.ArrayList;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author m78159
 */
public class LayeredPane extends javax.swing.JLayeredPane {
    public Panel p;
    public ArrayList<ExtendedKeys> sp;
    /**
     * Creates new form LayeredPanel
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public LayeredPane() {
        initComponents();
        this.setSize(500,340);
        p = new Panel();
        this.add(p,new Integer(0));
        sp = new ArrayList<>();
        int pos[] = {2,6,7,8,10};
        int conf[] = {60,60,60,80,50};
        for(int i : pos)
            sp.add(new ExtendedKeys(p.jl.get(i).getText()));
        //set positioning
        for(int i = 0; i < sp.size(); i++){
            //adding jButtons to frame - front layer
            this.add(sp.get(i),new Integer(300));
            sp.get(i).setLocation(p.jl.get(pos[i]).getX()-conf[i], p.jl.get(pos[i]).getY()-20);
            sp.get(i).setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
